### ISSUE TITLE
[Request] Remove Dependencies to Google Play Services on Android

### ISSUE THREAD

**Issue by rweickelt** [stipa/helphelp2#18]
Would it be possible to remove dependencies to google play services? They require the installation of the whole google apps package which I don't have and don't want to install on my phone. I'm using a Jolla running on Sailfish OS and featuring Alien Dalvik for Android support.

The same applies to Cyanogen Mod and other Custom ROMs. Even fairphone doesn't ship with google apps pre-installed.

**Comment by lstipakov** [comment]
Hello,

I don't plan to do it myself because of:
- Things like Google Maps and location services are depended on Google Play Services. 
- I don't have a phone without Google Play Services to test it.

However, you are welcomed to fork an app and do necessary changes.
