### ISSUE TITLE
Add release tags

### ISSUE THREAD

**Issue by johnjohndoe** [stipa/helphelp2#5]
Please maintain consistent releases by also adding Git tags and pushing them to this repository.
Please consider using [semantic versioning](http://semver.org/) for release tags.

``` bash
$ git checkout {some-release-commit}
$ git tag -a "v.1.0.0" -m "Short summary of the release."
$ git push -tags origin master
```

**Comment by lstipakov** [comment]
Done, https://github.com/help2/android/releases/tag/v1.5.0

**Comment by johnjohndoe** [comment]
You can also checkout the former versions such as db7a13e6a1ee232cddbdea1cb6e4ae6678d8c83f, add the tags and then push all the tags to GitHub.
